
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    project: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    project: backend    
---
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    project: database   
---
apiVersion: v1
kind: Namespace
metadata:
    name: monitoring