apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectivity-test-pod
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: connectivity-test-container
          image: ubuntu:latest
          command: ["sh", "-c", "apt update && apt install -y netcat  && nc -vz -w 5 backend-service.backend 5000 && nc -vz -w 5 redis.database 6379; sleep 3m"]
